### ISSUE TITLE
Force default workspace parent when creating a new workspace

### ISSUE THREAD

**Issue by Mari0nV** [ditrit/leto#111]
**Bug description**

When creating a new workspace, if we don't select a workspace parent and we click on Next, then the next step is empty except for a button Next that does not work.

**Steps to reproduce**

1. Click on New workspace
2. Fill the form except for the workspace parent button
3. Click on Next
4. The next step is empty and we can't click on Next

**Expected behavior**

Either the workspace parent button should be mandatory, or it should be defined as "root" by default.

**Screenshots**

After clicking on Next on the first step of workspace creation:

![Screenshot_20220615_144543](https://user-images.githubusercontent.com/23618241/173830972-49ce5d05-fc3e-487e-9a78-9b9d65781b66.png)

**Comment by Zorin95670** [comment]
Resolve in #133
