### ISSUE TITLE
Workspace creation form is not blocked with missing mandatory fields

### ISSUE THREAD

**Issue by Mari0nV** [ditrit/leto#125]
**Describe the bug**

When creating a workspace, the form is not blocked when we don't fill mandatory field and go to the next page.

**To Reproduce**

1. Click on New workspace
2. Click on Next
3. It goes to the next page.

**Expected behavior**

The Next button should be blocked and an error message should appear to tell the user to fill the missing mandatory field.

**Video capture**

https://user-images.githubusercontent.com/23618241/174636887-87894d5a-1160-4bd1-b1da-5564a60bd8a4.mp4

**Application (please complete the following information):**

- leto commit hash 063bca4f92aa15af2d004490a94d76df14d6e34d

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser Mozilla
- Version 101.0.1

**Comment by Zorin95670** [comment]
Resolved in #128

**Comment by Zorin95670** [comment]
Resolved in #128
