### ISSUE TITLE
Problème visuel sur la page d'authentification

### ISSUE THREAD

**Issue by treivax** [ditrit/leto#13]
**Bug :** sur la page d'authentification, la partie gauche (visuel avec logo Leto) disparaît en agrandissant la fenêtre en largeur).

**Comment by BrahimS** [comment]
Merci @treivax , ce n'ai pas un bug,  J'ai fait pour que l'éran prend cette allure en Full HD.

**Comment by BrahimS** [comment]
This issues is fixed
