### ISSUE TITLE
Add a workspace git config  to workspace tabs panel

### ISSUE THREAD

**Issue by BrahimS** [ditrit/leto#138]
## Description

**As a** user, I want to access to workspace git config 
**When** I get to a workspace page details
**than** I wnat to access information related to the workspace childs list on the panel tab : git config

### Scenario

 **Scenario** | Workspace git config list cards
 ------------ | -------------------------------------------------
 **Given**    |  The workspace details
 **When**     |  I click on the panel
 **Then**     | I want be able to see informations related to workspace git config

## Steps:
* Add a `gitConfigTabCard component`
* Add a composable file `gitConfigTabData`

**Comment by Mari0nV** [comment]
will this panel handle the update of git config?
does this issue means that issue https://github.com/ditrit/leto/issues/68 is not up to date anymore? or do we maintain it?

**Comment by Zorin95670** [comment]
Please update #68 instead of duplicate.
