### ISSUE TITLE
A duplicate drawing appears after component creation

### ISSUE THREAD

**Issue by Mari0nV** [ditrit/leto#164]
**Bug description**

When creating a component, sometimes there is a drawing of this component that stays on the screen even when we move it (the move works and we can see another drawing of the component following the cursor).

**To Reproduce**

1. Load (or create) a model 3D in the modelization panel.
2. Create a component.
3. Move it.
4. The component moves successfully.
5. A drawing of this component stays on the top left of the screen (we can't do anything with it, it's just a drawing).

**Expected behavior**

The fixed drawing of the component should not appear.

**Screenshot**

![image](https://user-images.githubusercontent.com/23618241/175912590-f386fecd-a716-4385-ba8b-6fe48f432493.png)

**Comment by Zorin95670** [comment]
I suspect that this bug come from a creation duplication of the component, because now with a unique name, we see two unique component generated.
