### ISSUE TITLE
Compile should happen on switch

### ISSUE THREAD

**Issue by Mari0nV** [ditrit/leto#184]
## Description

**As a** User

**When** I load a project into the modelization panel

**I want** to compile my project during the switch

**So that** I don't have to click on a compile button before switching

### Scenario

 **Scenario** | Switch view
 ------------ | -------------------------------------------------
 **Given**    | A project into the modelization panel
 **When**     | I click on the switch
 **Then**     | My project should compile
**And**        | The view should switch

## Constraints

- Remove compile button and integrate its behavior into the switch.
- If there is a compile issue, we should not be able to switch : block the switch and display an error message.

**Comment by BrahimS** [comment]
Solution One: Feature/compile on switch #196
Solution Two: Feature/compile button plus toggle #206
