### ISSUE TITLE
Add top menu bar with enriched model switch

### ISSUE THREAD

**Issue by Mari0nV** [ditrit/leto#84]
## Description

**As a** User

**When** I go the modelization panel

**I want** to have a top menu bar with the product name and an enriched model switch

**So that** I can switch easily between 3D representation and text

## Constraints

- The left and right panels should be hidden when switching to Text representation.
- Remove the stepper when we are on the modelization page

## Resources:

![CaptureLetoModeler_newmenu_up](https://user-images.githubusercontent.com/23618241/173016142-2ad2fc6d-6142-43b1-955f-ba7f1d83186e.png)

**Comment by BrahimS** [comment]
@Mari0nV  @Zorin95670 
Result : https://nextcloud.ditrit.io/index.php/s/XNCDJHdP7pADPc3
