### ISSUE TITLE
Update `GitProvider` of a `product`

### ISSUE THREAD

**Issue by Zorin95670** [ditrit/leto#89]
According to :
- #68 
- ditrit/gandalf#225
- ditrit/gandalf#227

## Steps:

* Update the `product` models to remove `GitUrl`
* Add to the `product` models the `GitProvider` model
* Add a store to manage the `ProductGitProvider` endpoint defined in the ditrit/gandalf#223
* Modify the form according the Story

## Blockers

- ditrit/gandalf#225
- ditrit/gandalf#227

**Comment by BrahimS** [comment]
You can check Design update [here](https://xd.adobe.com/view/b2cb743e-c2bd-48c2-8d2e-9f20f1ddc94e-e798/screen/bba79e3e-bb67-478b-bceb-4a47d6474e0f/)
